include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80
  DOCKER_BUILD_ARG_REACT_APP_PIWIK_URL: 'https://analytics.hel.ninja'
  DOCKER_BUILD_ARG_REACT_APP_PIWIK_ID: '18'
  DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: '$GL_SENTRY_DSN'
  DOCKER_BUILD_SASS_PATH: 'src/assets:node_modules/open-city-design/src/scss'

build-review:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_REACT_APP_API_URL: 'https://venepaikka-api.test.kuva.hel.ninja/graphql/'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'development'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'review'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_REACT_APP_API_URL: 'https://venepaikka-api.test.kuva.hel.ninja/graphql/'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'development'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'staging'
  only:
    refs:
      - master

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_REACT_APP_API_URL: 'https://api.hel.fi/berths/graphql/'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'production'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'production'
  only:
    refs:
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0

staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    POSTGRES_ENABLED: 0

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    POSTGRES_ENABLED: 0
