sudo: false
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
jobs:
  include:
    - stage: 'Test'
      name: 'Run code linting and test'
      script: yarn lint && yarn test:ci
    - stage: 'Build'
      name: 'Run (test) build'
      if: branch IN (master)
      script: yarn build
    - stage: 'Browser test'
      name: 'Run browser tests'
      if: type = cron
      script: yarn browser-test:ci

after_success:
  - codecov < coverage/lcov.info
