sudo: false
language: node_js
node_js:
  - '11'
cache:
  yarn: true
  directories:
    - node_modules
    - /home/travis/.cache/Cypress
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - cypress install
script:
  - yarn eslint './src/**/*.js'
  - yarn build
  - yarn test:ci
