version: '3'

services:
  web:
    container_name: berth-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '9000:9000'
    environment:
      - NODE_ENV='development'